### ISSUE TITLE
Chainlink Forking mainnet

### ISSUE THREAD

**Issue by ghost** [PatrickAlphaC/chainlink-hardhat#1]
Hello, I have tested this repo for local testing with main net forking but when trying to interact with the deployed Instance of chainlink the tx get reverted. I am trying to debug it, but I have failed till now. Can this sample work if I fork from the latest block, or I have to fork from the block that the specific chainlink Smart Contract is deployed or has a transaction?

**Comment by PatrickAlphaC** [comment]
Glad you liked the repo!

So what is the transaction you're looking to make? It should work if you fork from the latest block.

**Comment by ghost** [comment]
I have changed your sample a little bit so I can have it for many Chainlink Addresses. Here is my Contract:


```
// SPDX-License-Identifier: MIT
pragma solidity ^0.7.4;

import "@chainlink/contracts/src/v0.6/interfaces/AggregatorV3Interface.sol";

import "../inc/Base.sol";
import "../interfaces/IOracleModule.sol";
contract OracleModule is IOracleModule, Base {
    using SafeMathUpgradeable for uint256;
    uint256 public intervalTime; // 1 Hour

    struct Price {
        uint256 priceETH;
        uint256 chainTimestamp;
        uint256 lastUpdateTimestamp;
    }

    mapping(address => Price) internal prices;
    mapping(address => address) internal chainlink;

    function initialize() public initializer {
        OwnableUpgradeable.__Ownable_init();
        intervalTime = 60 * 60;
    }

    function updateOracleAddress(address _reserve, address _chainlink)
        external
        override
        onlyOwner
    {
        chainlink[_reserve] = _chainlink;
    }

    function clearOracleAddress(address _reserve) external override onlyOwner {
        chainlink[_reserve] = address(0);
    }

    function getPrice(address _reserve) external override returns (uint256) {
        if (
            prices[_reserve].lastUpdateTimestamp.add(intervalTime) <
            block.timestamp
        ) {
            updatePrice(_reserve);
        }
        return prices[_reserve].priceETH;
    }

    function updatePrice(address _reserve) internal {
        AggregatorV3Interface priceFeed = AggregatorV3Interface(
            chainlink[_reserve]
        );
        (, int256 price, , uint256 timeStamp, ) = priceFeed.latestRoundData();

        prices[_reserve].priceETH = uint256(price);
        prices[_reserve].chainTimestamp = timeStamp;
        prices[_reserve].lastUpdateTimestamp = block.timestamp;
    }
}
```

After storing the Pairs with `updateOracleAddress()` for each Pair: like this:
`OracleModule.updateOracleAddress(DAI.address, '0x773616E4d11A78F511299002da57A0a94577F1f4');`
I am using my function `getPrice()` that calls `updatePrice()`

**Comment by PatrickAlphaC** [comment]
Well, I can see your first issue is that you're using `import "@chainlink/contracts/src/v0.6/interfaces/AggregatorV3Interface.sol";` in a `v0.7` version of solidity. Could you try importing the newer package or using `v0.6` version of solidity? 

Also, knowing what error you're getting will be very helpful.

**Comment by ghost** [comment]
Thank you for your reply.
I couldn't find the methods for solidity 0.7 or neither found any information for that online.
https://github.com/smartcontractkit/chainlink/tree/develop/evm-contracts/src/v0.7/interfaces

> Also, knowing what error you're getting will be very helpful.

I couldn't debug the real issue since Alchemy has timeout problems today. But I just get reverted transaction.

**Comment by PatrickAlphaC** [comment]
Ah ok. Is there a chance you can use v0.6 for the moment?

**Comment by ghost** [comment]
@PatrickAlphaC I am sorry for wasting your precious time, it was something else totally unrelated. I had a mess on testing. Thank you! Btw it works perfectly even in solidity 0.7

**Comment by PatrickAlphaC** [comment]
No worries! I'm glad we were able to work it out!
